{
 "title": "Overview",
 "description": "Dashboard for the honey pot.",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Authentication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Authentication Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "cowrie",
     "rawSql": "SELECT\n $__timeGroupAlias(timestamp, $__interval),\n COUNT(*) AS value,\n \"logins\" AS metric \nFROM cowrie.auth WHERE $__timeFilter(timestamp) GROUP BY time ORDER BY time ASC "
    }
   ]
  },
  {
   "title": "Top Authentications",
   "type": "table",
   "description": "Most frequently used authentication.",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT username, password, COUNT(*) AS total from cowrie.auth WHERE $__timeFilter(timestamp) GROUP BY username, password ORDER BY total DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "stat",
   "description": "Failed attempts for the time period.",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cowrie",
     "rawSql": "SELECT COUNT(*) AS value FROM cowrie.auth WHERE $__timeFilter(timestamp) AND success = 0;"
    }
   ]
  },
  {
   "title": "Success",
   "type": "stat",
   "description": "Successful attempts for the time period.",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS value FROM cowrie.auth WHERE $__timeFilter(timestamp) AND success = 1;"
    }
   ]
  },
  { "title": "Interactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Location",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT c.country_code AS code, c.country AS name, latitude, longitude, COUNT(*) AS metric FROM (SELECT ip, geoip.country_code(ip) AS country_code FROM cowrie.sessions WHERE $__timeFilter(starttime)) s LEFT JOIN geoip.country_gps c ON s.country_code = c.country_code GROUP BY c.country_code, c.country;"
    }
   ]
  },
  {
   "title": "Top Countries",
   "type": "table",
   "description": "Most frequent countries.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT c.country_code AS code, c.country AS name, COUNT(*) AS total FROM (SELECT ip, geoip.country_code(ip) AS country_code FROM cowrie.sessions WHERE $__timeFilter(starttime)) s LEFT JOIN geoip.country_gps c ON s.country_code = c.country_code GROUP BY c.country_code, c.country ORDER BY total DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Downloads",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT url, COUNT(*) AS total from cowrie.downloads WHERE $__timeFilter(timestamp) GROUP BY url ORDER BY total DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "piechart",
   "description": "Most frequently used commnds.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT command, COUNT(*) AS total FROM (SELECT SUBSTRING_INDEX(input, ' ', 1) AS command FROM cowrie.input WHERE $__timeFilter(timestamp)) commands GROUP BY command ORDER BY total DESC LIMIT 10;"
    }
   ]
  }
 ]
}